/*
 * Tarea 02
 * Sistema Academico con conexion a Base de Datos
 * 
 * Estudiante: Daniel Somarribas Quir�s
 * Carnet: b57072
 * Mayo, 2016
 */
package Vista.Panel.Info;

import Controlador.CNTRL_Usuarios;
import Vista.Frame.Administrar.FRM_Usuarios;

/**
 *
 * @author DanielSQ
 */
public class JP_InfoUsuario extends javax.swing.JPanel {
    CNTRL_Usuarios controlador;
    FRM_Usuarios frame;

    /**
     * Creates new form JP_InfoUsuario
     */
    public JP_InfoUsuario() 
    {
        initComponents();
    }
    
    /**
     * Añade los controladores a los usuarios
     * @param controlador
     * @param frame
     */
    public void addController(CNTRL_Usuarios controlador,FRM_Usuarios frame)
    {        
        this.controlador = controlador;
        this.frame = frame;
    }
    
    /**
     * Devuelve el Usuario
     * @return
     */
    public String getUser()
    {
        return jtf_User.getText();
    }
    
    /**
     * Devuelve toda la información del usuario escrita en el frame
     * @return
     */
    public String[] getInfo()
    {
        String[] info = new String[3];
        
        info[0] = jtf_User.getText();
        info[1] = jtf_Nombre.getText();
        info[2] = jpf_Pass.getText();
        
        return info;
    }
    
    /**
     * Llena los campos de texto con la información del Usuario
     * @param nombre
     */
    public void fillField(String nombre)
    {
        jtf_Nombre.setText(nombre);
    }
    
    /**
     * Limpia los campos de texto
     */
    public void clearFields()
    {
        jtf_User.setText("");
        jtf_Nombre.setText("");
        jpf_Pass.setText("");
    }
    
    /**
     * Limpia el campo de Nombre
     */
    public void clearField()
    {
        jtf_Nombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Nombre = new javax.swing.JLabel();
        jl_User = new javax.swing.JLabel();
        jl_Pass = new javax.swing.JLabel();
        jpf_Pass = new javax.swing.JPasswordField();
        jtf_User = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();

        jl_Nombre.setText("Nombre");
        jl_Nombre.setToolTipText("Nombre Real");

        jl_User.setText("Usuario");
        jl_User.setToolTipText("Nombre de Usuario");

        jl_Pass.setText("Contraseña");
        jl_Pass.setToolTipText("Contrseña");

        jpf_Pass.setToolTipText("Contraseña");
        jpf_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpf_PassKeyPressed(evt);
            }
        });

        jtf_User.setToolTipText("Nombre de Usuario");
        jtf_User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_UserKeyReleased(evt);
            }
        });

        jtf_Nombre.setToolTipText("Nombre Real");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Pass)
                    .addComponent(jl_Nombre)
                    .addComponent(jl_User))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jpf_Pass)
                    .addComponent(jtf_User))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_User)
                    .addComponent(jtf_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Pass)
                    .addComponent(jpf_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_UserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_UserKeyReleased
         if(jtf_User.getText().equals(""))
        {
            frame.nadaConf();
        }
        else
        {
            controlador.buscar();
        }
    }//GEN-LAST:event_jtf_UserKeyReleased

    private void jpf_PassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_PassKeyPressed
        if(evt.getKeyCode()==10)
        {
            
            if(frame.agregarOpen == true)
            {
                controlador.agregarBase();
            }
        }
    }//GEN-LAST:event_jpf_PassKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Pass;
    private javax.swing.JLabel jl_User;
    private javax.swing.JPasswordField jpf_Pass;
    private javax.swing.JTextField jtf_Nombre;
    private javax.swing.JTextField jtf_User;
    // End of variables declaration//GEN-END:variables
}
