/*
 * Tarea 02
 * Sistema Acad�mico con conexi�n a Base de Datos
 * 
 * Estudiante: Daniel Somarribas Quir�s
 * Carnet: b57072
 * Mayo, 2016
 */
package Vista.Panel.Info;

import Controlador.CNTRL_Estudiantes;
import Controlador.CNTRL_Matriculas;
import Vista.Frame.Administrar.FRM_Estudiantes;
import Vista.Frame.Administrar.FRM_Matriculas;

/**
 *
 * @author DanielSQ
 */
public class JP_InfoEstudiante extends javax.swing.JPanel {
    CNTRL_Estudiantes controlador = null;
    CNTRL_Matriculas controladorMatriculas = null;
    FRM_Estudiantes frame = null;
    FRM_Matriculas matriculas = null;

    /**
     * Creates new form JP_InfoEstudiante
     */
    public JP_InfoEstudiante() {
        initComponents();
    }
    
    /**
     * Añade el controlador al campo de código
     * @param controlador
     * @param frame
     */
    public void addController(CNTRL_Estudiantes controlador, FRM_Estudiantes frame)
    {
        this.frame = frame;
        this.controlador = controlador;
        jtf_EstudianteID.setActionCommand("Buscar");
        jtf_EstudianteID.addActionListener(controlador);
    }
    
    /**
     * Añade el controlador al campo de código (Para matrículas)
     * @param controladorMatriculas
     * @param matriculas
     */
    public void addController(CNTRL_Matriculas controladorMatriculas, FRM_Matriculas matriculas)
    {
        this.controladorMatriculas = controladorMatriculas;
        this.matriculas = matriculas;
        jtf_EstudianteID.setActionCommand("Buscar");
        jtf_EstudianteID.addActionListener(controladorMatriculas);
    }
    
    /**
     * Devuelve el ID del Estudiante escrito en el frame
     * @return
     */
    public String getEstudianteID()
    {
        return jtf_EstudianteID.getText();
    }
    
    /**
     * Devuelve toda la información del estudiante escrita en el frame
     * @return
     */
    public String[] getInfo()
    {
        String[] info = new String[3];
        
        info[0] = jtf_EstudianteID.getText();
        info[1] = jtf_Nombre.getText();
        info[2] = jtf_Direccion.getText();
        
        return info;
    }
    
    /**
     * Llena los campos de texto con la información del Estudiante
     * @param info
     */
    public void fillFields(String[] info)
    {
        jtf_Nombre.setText(info[0]);
        jtf_Direccion.setText(info[1]);
    }
    
    /**
     * Limpia los campos de texto
     */
    public void clearFields()
    {
        jtf_EstudianteID.setText("");
        jtf_Nombre.setText("");
        jtf_Direccion.setText("");
    }
    
    /**
     * Limpia únicamente los campos de texto para nombre y dirección
     */
    public void clearPartialFields()
    {
        jtf_Nombre.setText("");
        jtf_Direccion.setText("");
    }
    
    /**
     * Establece los espacios de Nombre y Dirección como No Editables
     */
    public void setNoEditable()
    {
        jtf_Nombre.setEditable(false);
        jtf_Direccion.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_EstudianteID = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jtf_Direccion = new javax.swing.JTextField();
        jtf_Nombre = new javax.swing.JTextField();
        jtf_EstudianteID = new javax.swing.JTextField();

        jl_EstudianteID.setText("Código");

        jl_Nombre.setText("Nombre");

        jl_Direccion.setText("Dirección");

        jtf_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_DireccionKeyPressed(evt);
            }
        });

        jtf_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_DireccionKeyPressed(evt);
            }
        });

        jtf_EstudianteID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_DireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_EstudianteIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_EstudianteID)
                            .addComponent(jl_Nombre))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_Direccion)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jtf_Direccion)
                    .addComponent(jtf_EstudianteID))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_EstudianteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_EstudianteID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Direccion)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_EstudianteIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_EstudianteIDKeyReleased
        if(jtf_EstudianteID.getText().equals(""))
        {
            if(frame != null)
            {
                frame.nadaConf();
            }
        }
        else
        {
            if(controlador != null)
            {
                controlador.buscar();
            }
            if(controladorMatriculas != null)
            {
                controladorMatriculas.buscarEstudiante();
            }
        }
    }//GEN-LAST:event_jtf_EstudianteIDKeyReleased

    private void jtf_DireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_DireccionKeyPressed
        if(evt.getKeyCode()==10)
        {
            if(frame != null)
            {
                if(frame.agregarOpen == true)
                {
                    if(controlador != null)
                    {
                        controlador.agregar();
                    }
                }
            }
        }
    }//GEN-LAST:event_jtf_DireccionKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_EstudianteID;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jtf_Direccion;
    private javax.swing.JTextField jtf_EstudianteID;
    private javax.swing.JTextField jtf_Nombre;
    // End of variables declaration//GEN-END:variables
}
