/*
 * Tarea 02
 * Sistema Academico con conexion a Base de Datos
 * 
 * Estudiante: Daniel Somarribas Quir�s
 * Carnet: b57072
 * Mayo, 2016
 */
package Vista.Frame.Administrar;

import Controlador.CNTRL_MenuPrincipal;
import Controlador.CNTRL_Usuarios;
import Modelo.Archivo.ARCH_Usuarios;
import Modelo.Database.ConexionBD;
import Modelo.Metodos.MTDS_Usuarios;

/**
 *
 * @author DanielSQ
 */
public class FRM_Usuarios extends javax.swing.JFrame {
    CNTRL_Usuarios controlador;
    public boolean agregarOpen = false;
    String tipo = "";
    ARCH_Usuarios archivo;
    
    /**
     * Creates new form FRM_Usuarios
     * @param baseDatos
     * @param archivo
     */
    public FRM_Usuarios(ConexionBD baseDatos, ARCH_Usuarios archivo) {
        controlador = new CNTRL_Usuarios(this, baseDatos, archivo);
        initComponents();        
        addController(controlador);
        nadaConf();
    }
    
    public void configuracionInicial(CNTRL_MenuPrincipal controladorMenuPrincipal)
    {        
        
        controlador.configuracionInicial(controladorMenuPrincipal);
    }
    
        /**
     * Añade el controlador a los botones del frame
     * @param controlador
     */
    public void addController(CNTRL_Usuarios controlador)
    {
       jp_InfoUsuario.addController(controlador, this);
       jp_Botones.addController(controlador);
    }
    
    /**
     * Devuelve el nombre de usuario
     * @return
     */
    public String getUser()
    {
        return jp_InfoUsuario.getUser();
    }
    
    /**
     * Llena el campo de nombre con el nombre del usuario
     * @param nombre
     */
    public void fillField(String nombre)
    {
        jp_InfoUsuario.fillField(nombre);
    }
    
    public void clearPartialField()
    {
        jp_InfoUsuario.clearField();
    }
    
    /**
     * Devuelve la información completa escrita en el frame
     * @return
     */
    public String[] getInfo()
    {
        return jp_InfoUsuario.getInfo();
    }
    
    /**
     * Limpia todos los campos
     */
    public void clearFields()
    {
        jp_InfoUsuario.clearFields();
    }
    
    /**
     * Define la configuración para cuando no hay ningún botón disponible
     */
    public void nadaConf()
    {
        jp_Botones.nadaConf();
        agregarOpen = false;
    }

    /**
     * Configura los botones para cuando no hay ningún estudiante encontrado
     */
    public void noEntidadConf()
    {
        jp_Botones.noEntidadConf();
        agregarOpen = true;
    }
    
    /**
     * Configura los botones para cuando se ha encontrado un estudiante
     */
    public void siEntidadConf()
    {
        jp_Botones.siEntidadConf();
        agregarOpen = false;
    }
    
    public void setTipo(String tipo)
    {
        this.tipo = tipo;
        controlador.setTipo(tipo);
    }
    
    public MTDS_Usuarios getMetodos()
    {
        return controlador.getMetodos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_InfoUsuario = new Vista.Panel.Info.JP_InfoUsuario();
        jp_Botones = new Vista.Panel.Botones.JP_Botones();

        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_InfoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_InfoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.Panel.Botones.JP_Botones jp_Botones;
    private Vista.Panel.Info.JP_InfoUsuario jp_InfoUsuario;
    // End of variables declaration//GEN-END:variables
}
