/*
 * Tarea 02
 * Sistema Acad�mico con conexi�n a Base de Datos
 * 
 * Estudiante: Daniel Somarribas Quir�s
 * Carnet: b57072
 * Mayo, 2016
 */
package Vista.Panel.Botones;

import Controlador.CNTRL_Matriculas;

/**
 *
 * @author Daniel
 */
public class JP_BotonesDos extends javax.swing.JPanel {

    /**
     * Creates new form JP_BotonesMatricula
     */
    public JP_BotonesDos() 
    {
        initComponents();
    }
    
    public void addController(CNTRL_Matriculas controlador)
    {
        jbtn_Agregar.addActionListener(controlador);
        jbtn_Eliminar.addActionListener(controlador);
    }
    
    public void disableBoth()
    {
        jbtn_Agregar.setEnabled(false);
        jbtn_Eliminar.setEnabled(false);
    }
    
    public void agregarConf()
    {
        jbtn_Agregar.setEnabled(true);
        jbtn_Eliminar.setEnabled(false);
    }
    
    public void eliminarConf()
    {
        jbtn_Agregar.setEnabled(false);
        jbtn_Eliminar.setEnabled(true);
    }
    
    public void enableBoth()
    {
        jbtn_Agregar.setEnabled(true);
        jbtn_Eliminar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_Agregar = new javax.swing.JButton();
        jbtn_Eliminar = new javax.swing.JButton();

        jbtn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        jbtn_Agregar.setToolTipText("Realizar Matrícula");
        jbtn_Agregar.setActionCommand("Agregar");

        jbtn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        jbtn_Eliminar.setToolTipText("Eliminar Matrícula");
        jbtn_Eliminar.setActionCommand("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtn_Agregar)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Eliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_Agregar)
                    .addComponent(jbtn_Eliminar))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Agregar;
    private javax.swing.JButton jbtn_Eliminar;
    // End of variables declaration//GEN-END:variables
}
