/*
 * Tarea 02
 * Sistema Academico con conexion a Base de Datos
 * 
 * Estudiante: Daniel Somarribas Quir�s
 * Carnet: b57072
 * Mayo, 2016
 */
package Vista.Panel.Botones;

import Controlador.CNTRL_Cursos;
import Controlador.CNTRL_Estudiantes;
import Controlador.CNTRL_Usuarios;

/**
 *
 * @author DanielSQ
 */
public class JP_Botones extends javax.swing.JPanel {

    /**
     * Creates new form JP_Botones
     */
    public JP_Botones() {
        initComponents();
    }
    
    /**
     * Añade el controlador de Estudiante a los botones
     * @param controlador
     */
    public void addController(CNTRL_Estudiantes controlador)
    {
        jbtn_Agregar.addActionListener(controlador);
        jbtn_Modificar.addActionListener(controlador);
        jbtn_Eliminar.addActionListener(controlador);
    }
    
    /**
     * Añade el controlador de Curso a los Botones
     * (Sobrecarga de método)
     * @param controlador
     */
    public void addController(CNTRL_Cursos controlador)
    {        
        jbtn_Agregar.addActionListener(controlador);
        jbtn_Modificar.addActionListener(controlador);
        jbtn_Eliminar.addActionListener(controlador);
    }
    
    /**
     * Añade el controlador de Usuario a los Botones
     * (Sobrecarga de método)
     * @param controlador
     */
    public void addController(CNTRL_Usuarios controlador)
    {        
        jbtn_Agregar.addActionListener(controlador);
        jbtn_Modificar.addActionListener(controlador);
        jbtn_Eliminar.addActionListener(controlador);
    }
    
    /**
     * Establece que los botones estén apagados cuando no hay nada disponible
     */
    public void nadaConf()
    {
        jbtn_Agregar.setEnabled(false);
        jbtn_Modificar.setEnabled(false);
        jbtn_Eliminar.setEnabled(false);
    }
    
    /**
     * Deshabilita los botones de Modificar y Eliminar
     */
    public void noEntidadConf()
    {
        jbtn_Agregar.setEnabled(true);
        jbtn_Modificar.setEnabled(false);
        jbtn_Eliminar.setEnabled(false);
    }
    
    /**
     * Deshabilita el botón de Agregar
     */
    public void siEntidadConf()
    {
        jbtn_Agregar.setEnabled(false);
        jbtn_Modificar.setEnabled(true);
        jbtn_Eliminar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_Agregar = new javax.swing.JButton();
        jbtn_Modificar = new javax.swing.JButton();
        jbtn_Eliminar = new javax.swing.JButton();

        jbtn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        jbtn_Agregar.setToolTipText("Agregar");
        jbtn_Agregar.setActionCommand("Agregar");

        jbtn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        jbtn_Modificar.setToolTipText("Modificar");
        jbtn_Modificar.setActionCommand("Modificar");

        jbtn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        jbtn_Eliminar.setToolTipText("Eliminar");
        jbtn_Eliminar.setActionCommand("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtn_Agregar)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Modificar)
                .addGap(18, 18, 18)
                .addComponent(jbtn_Eliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_Agregar)
                    .addComponent(jbtn_Modificar)
                    .addComponent(jbtn_Eliminar))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_Agregar;
    private javax.swing.JButton jbtn_Eliminar;
    private javax.swing.JButton jbtn_Modificar;
    // End of variables declaration//GEN-END:variables
}
